### ISSUE TITLE
To add the function of closing the Dropoff button

### ISSUE THREAD

**Issue by Omgise** [GTNewHorizons/InventoryBogoSorter#8]

**Comment by Caedis** [comment]
What?

**Comment by Omgise** [comment]
It is just that this button cannot be disabled through the configuration file
![image](https://github.com/user-attachments/assets/b4e39000-5cab-4acc-ad50-79d1bd82bc11)

**Comment by Omgise** [comment]
And it seems that there are still other problems with this button

https://github.com/user-attachments/assets/09d063e0-663b-40c8-a25b-4a4bbe4e2b67

**Comment by Omgise** [comment]
It seems that it will also crash
[crash-2024-12-22_10.41.30-server.txt](https://github.com/user-attachments/files/18220600/crash-2024-12-22_10.41.30-server.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/18220601/fml-client-latest.log)
